### ISSUE TITLE
how to get svg dataurl 

### ISSUE THREAD

**Issue by sajumani** [zenozeng/p5.js-svg#149]
Hi,

i need to get dataUrl when click on the design.

**Comment by zenozeng** [comment]
You can use the following code:

```javascript
var graphics = createCanvas(w, h, SVG);
// do sth...
var dataurl = graphics.elt.toDataURL('image/svg+xml');
```

**Comment by zenozeng** [comment]
Do you think I should add a method (like p5.prototype.getSerializedSVG) for this?

**Comment by sajumani** [comment]
yes, that will be better to get Dataurl after draw some patterns with mouse events.

**Comment by sajumani** [comment]
one more doubt,

Is this possible to load stored dataUrl to other canvas ...???

**Comment by zenozeng** [comment]
You can use:
```javascript
svg = loadSVG(dataURL);
image(svg, x, y, w, h);
```

**Comment by sajumani** [comment]
how can i get the dataUrl on click event...???

**Comment by zenozeng** [comment]
@sajumani I created a example for this: http://zenozeng.github.io/p5.js-svg/examples/#click

**Comment by sajumani** [comment]
Thank you so much, you are very helpful 
One final help
how can i create new cnvas from this dataurl ...??

**Comment by zenozeng** [comment]
```javascript
function setup() {
    createCanvas(w, h, SVG);
    svg = loadSVG(dataURL); // convert dataurl to SVG Element
    image(svg, x, y, w, h); // Draw the SVG Element
}
```

**Comment by sajumani** [comment]
ReferenceError: loadSVG is not defined

**Comment by zenozeng** [comment]
Which version of p5.SVG you are using?

**Comment by sajumani** [comment]
p5.svg v0.3.0

**Comment by zenozeng** [comment]
Can you try p5.svg@0.4.6?

https://github.com/zenozeng/p5.js-svg/releases

**Comment by sajumani** [comment]
p.setup = function () {
 canvas = p.createCanvas(previewWidth, previewHeight,p.SVG);
    canvas.id('canvas_preview_section');
    console.log(dataURL);
    svg = p.loadSVG(dataURL); // convert dataurl to SVG Element
  };

  p.draw = function () {
   p.image(svg, 0, 0, 100,100); // Draw the SVG Element
}


ERROR: TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement.

**Comment by zenozeng** [comment]
Sorry, my bad. I will fix it in next release.

**Comment by zenozeng** [comment]
Sorry, my demo code above is not right.
loadSVG is async.

Checkout this example: http://zenozeng.github.io/p5.js-svg/examples/#dataurl

**Comment by zenozeng** [comment]
BTW, p5.js@0.5.0 was out:
https://github.com/zenozeng/p5.js-svg/releases/tag/v0.5.0

**Comment by sajumani** [comment]
thanks great support from your side...

**Comment by sajumani** [comment]
![untitled 5](https://cloud.githubusercontent.com/assets/7368727/9868627/ed30eb7a-5b98-11e5-918f-ed3670e8afb9.png)


one final problem, we can't create circle like this...

am trying to make semi circle on four corner, Could you help me out

**Comment by sajumani** [comment]
MousePress() working everywhere .

am trying to make click even only on canvas 
 canvas = p.createCanvas(200,  200,p.SVG);
canvas.mousePressed(p.drawonPreview); // attach listener for

TypeError: ctx.elt.addEventListener is not a function
	

ctx.elt.addEventListener(ev, f, false);

**Comment by sajumani** [comment]
Can we have , 

p5 js load SVG() On complete callback function...??

**Comment by zenozeng** [comment]
canvas.mousePressed is not supported yet. I add this feature to plan of p5.SVG@0.6.0.
If you want to do it now, maybe you can use addEventListener of `canvas.getContext('2d').elt.svg`.

**Comment by zenozeng** [comment]
As for semi circle, can you show your p5.js code to draw it?

**Comment by zenozeng** [comment]
And what do you mean by saying `on complete callback`?

**Comment by sajumani** [comment]
am asking you for semi circle , that i given PSD file.

callback function means , we can call custom function ,after loadSVG() process complete

Jquery Asynchronous language,  i want to execute some function after LoadSVG() process complete

**Comment by sajumani** [comment]
i want to draw like this 
![shape](https://cloud.githubusercontent.com/assets/7368727/9876397/878017ca-5bd3-11e5-98dd-0e50d17afd38.png)

**Comment by zenozeng** [comment]
@sajumani It's not possible with loadSVG. But I can add `image(dataurl, args)` in next release.
What do think about it?

**Comment by zenozeng** [comment]
@sajumani As for simi circle, have a look at http://p5js.org/reference/#p5/arc

**Comment by sajumani** [comment]
Arc() will not support here, can you make function for this....??

**Comment by sajumani** [comment]
Sure, you have to write function for image(dataurl, args), It will support all developers

**Comment by zenozeng** [comment]
```javascript
createCanvas(100, 100);
arc(45, 55, 100, 100, HALF_PI, PI);
```

It this what you want?

**Comment by sajumani** [comment]
no not like that...i will show the screenshot...
![arc](https://cloud.githubusercontent.com/assets/7368727/9951977/05c632d0-5dec-11e5-8126-837c4024b51b.png)

**Comment by sajumani** [comment]
am waiting for your reply....!!!

**Comment by zenozeng** [comment]
Sorry, I was too busy these days and fotgot to reply this thread. What do
you want to draw? The black area with 2 lines and 1 arc?

**Comment by sajumani** [comment]
yes exactly..The black area with 2 lines and 1 arc

**Comment by zenozeng** [comment]
OK. I will create a demo for you later.

**Comment by sajumani** [comment]
i don't want you to be waste your time for me...can i get the code..??i will implement with my application

**Comment by zenozeng** [comment]
Checkout these 2 pages:

- http://p5js.org/tutorials/

- http://p5js.org/examples/

**Comment by sajumani** [comment]
it was not help me out...

**Comment by zenozeng** [comment]
```javascript
function setup() {
    createCanvas(600, 200, SVG);
    background(255);
    fill(128);
    beginShape();
    vertex(0, 0);
    vertex(0, 200); // Line from 0, 0 to 0, 200
    // http://p5js.org/reference/#/p5/bezierVertex
    // Curve from 0, 200 to 200, 0
    bezierVertex(0, 0, 0, 0, 200, 0);
    vertex(0, 0);
    endShape();
    noLoop();
}

function draw() {
}
```

Try this code.

**Comment by zenozeng** [comment]
Also checkout http://p5js.org/reference,
There are many functions described in that page.

**Comment by zenozeng** [comment]
The demo for code above: http://zenozeng.github.io/p5.js-svg/examples/#shape
