### ISSUE TITLE
Does not work with p5js editor (run in browser mode)

### ISSUE THREAD

**Issue by bmoren** [zenozeng/p5.js-svg#165]
This will not work with p5js editor even when toggling the 'run in browser' option and running that in chrome. 

This might be helpful to include as a limitation or as a future fix for people using that editor.

**Comment by zenozeng** [comment]
p5.js-svg is not included in p5js editor's default libraries.
![image](https://cloud.githubusercontent.com/assets/2544489/17077361/b974cece-5100-11e6-97a1-c0fc27144a92.png)


So, for now, you have to add p5.svg.js to libraries and add a reference in index.html.

**Comment by bmoren** [comment]
I'm aware that it is not included in the default libraries. The issue is that it will not render an SVG when using the editor's built in web server. You must use an external editor such as atom, and then set up a simple web server. At least this is my experience.

**Comment by vincentsijben** [comment]
Tested this with 1.0.5 and it works perfectly when adding the ```<script src="https://unpkg.com/p5.js-svg@1.0.5"></script>``` as a reference as zenozeng suggested.
![image](https://user-images.githubusercontent.com/36117924/120922333-d25cfb80-c6c8-11eb-880e-8dfe7bd36b92.png)

**Comment by bmoren** [comment]
This issue was from the old desktop p5.js editor (before the web based editor existed) given that it's seemingly working now this can be closed.

**Comment by zenozeng** [comment]
@vincentsijben Thank you for testing the new version.
