### ISSUE TITLE
load SVG works , but can't see it in canvas 

### ISSUE THREAD

**Issue by dattasaurabh82** [zenozeng/p5.js-svg#168]
I can see it load in the html file , but can't see it in canvas.. 
I was trying the example of manipulating. The svg file loads and everything but can't see it . 
I downloaded the test.svg from your repo just to error check with my custom svgs.. No result..

**Comment by noponies** [comment]
I have the same issue. loadSVG fails with an 'undefined' error.

**Comment by alexszilagyi** [comment]
Any updates on this? @zenozeng

**Comment by nightshining** [comment]
I think I'm having the same issue. I see '...loading' on my screen but nothing appears. In my terminal window I see that my 'test.svg' 'p5.min.js' 'p5.svg.js' all loaded properly.

**Comment by vincentsijben** [comment]
you could fix this by adding 

this._decrementPreload();

after 

if (successCallback) {
  successCallback(element);
}

in the p5.prototype.loadSVG function

**Comment by zenozeng** [comment]
@vincentsijben Thanks!
