### ISSUE TITLE
resetMatrix() not working

### ISSUE THREAD

**Issue by dannewoo** [zenozeng/p5.js-svg#170]
Hey @zenozeng, I have been using the svg library in my Creative Coding class and for the most part its working great! 

I just had a student come across a conflict when using the resetMatrix() function and wanted to add it to the issues. It seems like it doesnt reset when using the SVG renderer.

Thanks!

**Comment by zenozeng** [comment]
![8282EDE0-92F2-4C12-8C96-A1A745BF0011](https://user-images.githubusercontent.com/2544489/116452600-79f83a00-a890-11eb-8bbd-4a2ce90472be.jpeg)

**Comment by zenozeng** [comment]
https://github.com/gliffy/canvas2svg/pull/83
