### ISSUE TITLE
some bugs I found

### ISSUE THREAD

**Issue by makeyourownalgorithmicart** [zenozeng/p5.js-svg#171]
I tried to use this library and wrote up my experience [here](http://makeyourownalgorithmicart.blogspot.co.uk/2018/03/creating-svg-with-p5js.html).

A summary of what I found as bugs/issues:

- ellipse() needs all 4 arguments, recent p5js can take 3 when drawing circles
- updating the code, refreshing the tab doesn't work, often leaving missing elements or no drawing at all, workaround is to close tab and open a new one .. 

I tested with the latest Safari, Firefox and I think Chrome too.

**Comment by vincentsijben** [comment]
The ```ellipse()``` function works with 3 arguments now (tested with 1.0.5).
I don't seem to have the same issue updating/refreshing.
