### ISSUE TITLE
save(); bug

### ISSUE THREAD

**Issue by 5yF0Rc3** [zenozeng/p5.js-svg#176]
After some testing the function save() for the svg will only work if you setting
`  noFill(); //or fill(0);`
and `stroke(0);`
into the setup() function. (color desn't matter)
Maybe I am missing something but it worked for me.
Using: 
p5.js-svg.js: Version v0.6.0-alpha.0
p5.js: Version 1.0.0

**Comment by hillmark** [comment]
Thanks for this workaround. I can confirm the exported filed is truncated and malformed without setting fill and stroke.

**Comment by andreasvirkus** [comment]
Even when calling `noFill()` and `stroke(0)` in my setup, I'm still not getting anything rendered into my "canvas" 🤔 

Instead, i'm seeing thousands of base64 requests in my Network tab. I'm guessing this shouldn't be happening, right?


https://user-images.githubusercontent.com/9140811/106669097-d3afd780-65b3-11eb-8642-f16c443155cb.mov

**Comment by vincentsijben** [comment]
@5yF0Rc3 @andreasvirkus can you test again with your code, or provide some examples?
I can't seem to reproduce this with the latest version (I just commented out the ```strokeWeight(2); stroke('#ED225D');``` from the exporting example in a local test).

**Comment by vincentsijben** [comment]
For the example "Exporting SVG" on line 1470 it checks for styleEmpty, which is rgba(0,0,0,0). But if you don't set stroke, the actual value is ```#000000```. 

If I add ```if(ctx.strokeStyle === "#000000") ctx.strokeStyle = "rgba(0,0,0,1)";``` right before ```ctx.beginPath();``` it works.

**Comment by vincentsijben** [comment]
For the example "Exporting SVG" I've tested a line and rectangle use case with or without setting stroke and/or fill in setup.

If I add 
```
if (style.svgAttr === "fill" && value.indexOf("rgba") == -1) value = "rgba(255,255,255,1)";
if (style.svgAttr === "stroke" && value.indexOf("rgba") == -1) value = "rgba(0,0,0,1)";
``` 
right before linenumber 397 it works for this usecase. @zenozeng can probably find a more elegant way of fixing this 👍

**Comment by zenozeng** [comment]
![F5A678D0-9485-469C-8D29-C3F0614DEB66](https://user-images.githubusercontent.com/2544489/121852711-73c7fb00-cd22-11eb-846b-f0c32158fbab.jpeg)
![862508D1-97AE-4A05-BA72-FF607F35D46E](https://user-images.githubusercontent.com/2544489/121852725-788caf00-cd22-11eb-9966-279ae65b34f8.jpeg)

**Comment by zenozeng** [comment]
Fixed in p5.js-svg@1.0.6
