### ISSUE TITLE
Is this project live?

### ISSUE THREAD

**Issue by everythingability** [zenozeng/p5.js-svg#177]
https://editor.p5js.org/remarkability/sketches/4OSEIA15H

Any ideas why this doesn't work? Click to save. The SVG won't open...

**Comment by aaronpenne** [comment]
Your example works for me, clicking the image gives a download prompt window. I'm on a Macbook (Catalina) using Firefox 84.0.2

**Comment by andreasvirkus** [comment]
@aaronpenne the resulting SVG has another nested SVG element, that's empty:

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="800" height="800" viewBox="0 0 800 800">
  <defs/>
  <g transform="scale(1,1)">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="200" y="100" width="400" height="400" viewBox="0, 0, 396, 486">
      <g id="Layer_1"></g>
    </svg>
  </g>
</svg>
```

**Comment by aaronpenne** [comment]
Ah you are right, I misread the issue thinking the problem was with the download. Yup same issue for me, upon opening the download I get an error. Although the error I get is:
```
XML Parsing Error: unclosed token
Location: file:///Users/apenne/Downloads/untitled-4.svg
Line Number 3, Column 5:
    <path d="M299.029,430.35 ......,308.535 C86.518,308.423 86.43,308.331 86.459,308.331 L86.553,308.331" fill="
----^
```
