### ISSUE TITLE
dist folder and release update

### ISSUE THREAD

**Issue by vincentsijben** [zenozeng/p5.js-svg#184]
When running the demo.html in the root of this repo, it references a dist folder, which is deleted.

Could you also add a new release for 1.0.5? 

Thanks!

**Comment by zenozeng** [comment]
@vincentsijben 

Dist files are published to npm and unpkg, and can be found here: 
- https://unpkg.com/browse/p5.js-svg@1.0.5/dist/
- https://unpkg.com/p5.js-svg@1.0.5/demo.html

To build dist files after cloning repo, you can run:
```bash
npm install
npm run build
```

**Comment by vincentsijben** [comment]
Yes. 
Maybe put that in readme and delete the demo.html in this repo or is that necessary for npm?
