### ISSUE TITLE
Glad you got back to this project ! 

### ISSUE THREAD

**Issue by amehowc** [zenozeng/p5.js-svg#188]
Hey ! Amazing news that you brought back this super useful library ! 

Here a makeshift version i did for myself where i investigated the issue and put up a couple fixes in the library to remove the <g> attributes stacking and the background() function not clearing the stack of items. Don't know if you're interested in that but here it is ! 

https://github.com/amehowc/CREATIVECODING/tree/main/p5.SVG_Fixed

I dont know if you solved all the issues yet but i can help if needed!

**Comment by zenozeng** [comment]
@amehowc  Thanks! 😊 Would you like to try the latest v1.1.0 version, it is compatible with p5.js v1.4.0. And `the background() function not clearing the stack of items ` issue was fixed in v1.0.7. See https://github.com/zenozeng/p5.js-svg/blob/main/CHANGELOG.md.
