### ISSUE TITLE
p5.js-svg seems not compatible with p5.min.js

### ISSUE THREAD

**Issue by MisterKangaroo** [zenozeng/p5.js-svg#189]
If you are working on a template that uses p5.min.js instead of the standard p5.js the SVG isnt generated properly... and debugging doesnt work as it normally would.

Possible solution:
In the index.html replace the p5.min.js with the standard p5.js

**Comment by zenozeng** [comment]
@MisterKangaroo 

Hi, p5.js-svg@1.0.8 was tested with p5@1.3.1/lib/p5.min.js, it should be compatible with p5.min.js.
See https://github.com/zenozeng/p5.js-svg/blob/894919be025a6815876c6820f7ad483d79b22fdc/karma.conf.js#L15

Are there any specific error messages and steps to reproduce?
