### ISSUE TITLE
push - pop not considered

### ISSUE THREAD

**Issue by robwieringa** [zenozeng/p5.js-svg#191]
It looks like push/pop is ignored in SVG mode. 
See the attached example. When removeing the SVG parameter all blue boxes align (as they should)
[example.txt](https://github.com/zenozeng/p5.js-svg/files/6754147/example.txt)

**Comment by zenozeng** [comment]
@robwieringa  Thank you for reporting the bug. It is fixed in v1.1.1.

**Comment by robwieringa** [comment]
Great. Thanks for the quick solve.

Rob

**Comment by ixley** [comment]
Awesome!  +1 👍 Thanks for the quick fix 😄
