### ISSUE TITLE
svg interactivity

### ISSUE THREAD

**Issue by flocknester** [zenozeng/p5.js-svg#194]
Hi, love this exporter! When I export to svg I lose all mouse interactivity and dropdown functionality etc., is there anyway to keep that in my svg that's exported?? Thanks!

**Comment by zenozeng** [comment]
@flocknester Sorry, I think it's not possible for now. Keeping mouse interactivity in exported svg requires rewriting the whole p5.js to work in svg's script element. That's enormous work.

**Comment by flocknester** [comment]
Hi,

Thanks for the response, I appreciate you letting me know. I've begun to
learn d3 in order to have this capability.

best,

flocknester
