### ISSUE TITLE
mouseClicked does not seems to work

### ISSUE THREAD

**Issue by Sladix** [zenozeng/p5.js-svg#196]
Here is a sketch to reproduce the issue : https://editor.p5js.org/sladix/sketches/IJ8NfG8zP

**Comment by felipex** [comment]
It seems that the event is attached to the div "Pane vertical Pane2", this is the div that englobes the whole preview panel (beyond the gray area). When you click in this region the mouseClicked is trigged.
I think this explanation is a bit confusing, but  i hope this could help. I couldn't do better. :(

**Comment by zenozeng** [comment]
@Sladix  Thanks for reporting this bug, it should be fixed with p5.js-svg@1.3.1.
