### ISSUE TITLE
Allow querySVG() as function of p5.Graphics instance

### ISSUE THREAD

**Issue by chrsmlls333** [zenozeng/p5.js-svg#199]
I think my issue title is clear, but [querySVG](https://github.com/zenozeng/p5.js-svg/blob/464ab6dd13ba2f8ff72a63f28af96757851e9810/src/element.js#L10) is only currently usable as a global function on the renderer canvas element, not on other SVGCanvasElement objects.

**Comment by zenozeng** [comment]
This feature may be added in the next major version.

**Comment by zenozeng** [comment]
@chrsmlls333 Hi, p5.js-svg@1.3.0 is released, and querySVG() is now able to be called on p5.Graphics instance, example:

```javascript
new p5(function(p) {
     p.setup = function() {
         p.createCanvas(100, 100, p.SVG);
         let pg = p.createGraphics(100, 100, p.SVG);
         pg.ellipse(0, 0, 100, 100);
         expect(pg.querySVG('path')).to.have.lengthOf(1);
     };
 });
```
