### ISSUE TITLE
Example request: using pg.js-svg with p5 in instance mode?

### ISSUE THREAD

**Issue by hristod** [zenozeng/p5.js-svg#200]
I am currently trying to use p5.js-svg with p5 in instance mode, but couldn't find any instructions on how to do that.

**Comment by zenozeng** [comment]
@hristod I added an example here: https://github.com/zenozeng/p5.js-svg/blob/main/examples/instance/main.js

Feel free to reopen this issue if further documentation is required.

**Comment by hristod** [comment]
Thank you so much! It's so simple and elegant...
