### ISSUE TITLE
loadPixels() - Feature request

### ISSUE THREAD

**Issue by scoresmexico** [zenozeng/p5.js-svg#203]
Getting pixel colors at least.

Thanks

**Comment by zenozeng** [comment]
<img width="1392" alt="截屏2022-02-04 下午1 58 51" src="https://user-images.githubusercontent.com/2544489/152480088-62b10caa-0897-4f0b-8d1e-92770f487978.png">

loadPixels test case added.

**Comment by zenozeng** [comment]
@scoresmexico Hi, an experimental async version of loadPixels was added in p5.js-svg@1.3.0. This function is async due to limitations in drawing SVG onto canvas.
