### ISSUE TITLE
ReferenceError: SVG is not defined

### ISSUE THREAD

**Issue by vanviethieuanh** [zenozeng/p5.js-svg#216]
Hello! I add the script tag to my project and it say that SVG is not defined so I try to run on the [example site of p5js](https://editor.p5js.org/dannyrozin/sketches/r1djoVow7). But it print out the same error. Thanks!

**Comment by zenozeng** [comment]
@vanviethieuanh Hi, you can try p5.js v1.4.x, p5.js-svg v1.3.x is compatible with p5.js v1.4.x. The version of your p5.js (0.7.1) is a little bit old. Feel free to reopen this issue if it happens when using p5.js 1.4.x and p5.js-svg 1.3.x.

**Comment by amcc** [comment]
Its worth noting perhaps that the p5.js-svg import needs to be after the p5.js import. I certainly needed to do this in the online editor:
https://editor.p5js.org/amcc/sketches/jE8VuGHNx
