### ISSUE TITLE
Typescript type declarations

### ISSUE THREAD

**Issue by marcw** [zenozeng/p5.js-svg#223]
Hello and thanks for the library. 

This is a bit of a niche feature request: It would be absolutely awesome to provide type declaration for Typescript users. 

Many thanks

**Comment by PeterShershov** [comment]
Not niche at all :)

**Comment by zenozeng** [comment]
@PeterShershov @marcw 

Hi, I just rewrote the entire lib in TypeScript and released the new version v1.5.1. If you have time, you can try it out. Additionally, I also added a TypeScript + Vite example here: https://github.com/zenozeng/p5.js-svg/blob/main/examples/vite/src/main.ts

**Comment by PeterShershov** [comment]
@zenozeng thanks man!

**Comment by PeterShershov** [comment]
@zenozeng Hey, I just tried the Vite example and I'm getting the following error when trying to run it:
<img width="1436" alt="image" src="https://github.com/zenozeng/p5.js-svg/assets/16524839/8ee3dcdc-7f29-4091-97b8-cd70cad19ae5">

Here's my code (same as the example):
```ts
import "./style.css";
import p5 from "p5";
import init, { p5SVG } from "p5.js-svg";

init(p5);

const sketch = (p: p5SVG) => {
	p.setup = () => {
		p.createCanvas(400, 400, p.SVG);
	};

	p.draw = () => {
		p.background(220);
		p.ellipse(50, 50, 80, 80);
	};
};

new p5(sketch, document.body);
```
