### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by songproducer** [zenozeng/p5.js-svg#237]
Hi, I built v1.3.3 but get get this error in the console:
```
index.js:28 Uncaught ReferenceError: module is not defined
    at index.js:28:1
(anonymous) @ index.js:28
```

**Comment by zenozeng** [comment]
@songproducer Hi, I just added an example using vite here: https://github.com/zenozeng/p5.js-svg/blob/main/examples/vite/src/main.ts

If the issue is not resolved, feel free to reopen it.
