### ISSUE TITLE
High CPU load after long time running

### ISSUE THREAD

**Issue by zenozeng** [zenozeng/p5.js-svg#32]

**Comment by ianisl** [comment]
Thanks a lot for this library, very useful!

I've started playing with some simple sketches and noticed a huge slowdown after a few seconds of use. 

Saving the SVG and opening it in Illustrator, I noticed there was a huge number of nested nodes. It seems every call of p5.js' `draw` method adds a new `g` node as a child of the already existing `g` node inside the `svg` element created by p5.js-svg. In other words, every frame gets added to the DOM, although only the last one is visible.

A quick workaround is calling the `__clearCanvas` method of the Context at the beginning of p5.js' `draw`:

```
let renderer;

setup() {
  renderer = createCanvas(100, 100, SVG);
}

draw() {
  renderer.drawingContext.__clearCanvas();
  // Do the drawing
}
```

**Comment by zenozeng** [comment]
Thanks @ianisl
