### ISSUE TITLE
image(SVGGraphics, args) in Canvas renderer 

### ISSUE THREAD

**Issue by zenozeng** [zenozeng/p5.js-svg#78]
Might be useful:

- https://bugzilla.mozilla.org/show_bug.cgi?id=558188

**Comment by zenozeng** [comment]
This could be very hard. Because there is no way to synchronously draw \<svg\> element to canvas.
The behavior of this needs discussion.

**Comment by zenozeng** [comment]
I don't know, but if p5.js could provide something like await?

**Comment by dannewoo** [comment]
Hmmm can you explain this a bit more? Why would this be important to include?

**Comment by zenozeng** [comment]
So assume we have a \<svg\> Graphics, and we want to draw that on our existing canvas. We use `image(svgGraphics, x, y)`, so you can draw our \<svg\> on canvas. However, I could not find a way to do this. Because canvas could not draw \<svg\> directly. We have to use async way.
```javascript
var img = new Image();
img.onload = function() {
  ctx.drawImage(img);
}
img.src = dataURL
```

So, in the following code, the result could be unpredictable:

```javascript
createCanvas(w, h);
svg = createGraphics(width, height, 'svg');
svg.rect(args);
image(svg, args); // we don't know when it will finish
rect(args); // we will never know the rect is above the image or below, because image is loaded in async way
```

**Comment by dannewoo** [comment]
Ah understood. This might be a question for @lmccart or @shiffman. Also how are things going on the PDF export?

**Comment by zenozeng** [comment]
@dannewoo I just finished [createGraphics(w, h, 'svg')](https://github.com/zenozeng/p5.js-svg/blob/master/src/rendering/svg.js#L19), which is needed by p5.pdf. And I have built a draft for p5.pdf: https://github.com/zenozeng/p5.js-pdf/blob/dev/pdf.js. Once my final exam (in 2015-07-11) ends, and I will have more time and will working on it then. I hope that could be finished in a few days after 2015-07-11.

**Comment by zenozeng** [comment]
p5.pdf will be based on window.print and css3's @page.

**Comment by dannewoo** [comment]
@zenozeng sounds good thanks for the update!

**Comment by zenozeng** [comment]
Still no good luck.

See also: http://www.w3.org/html/wg/drafts/2dcontext/master/

1.1.9 Image sources for 2D rendering contexts

Several methods in the CanvasRenderingContext2D API take the union type CanvasImageSource as an argument.

This union type allows objects implementing any of the following interfaces to be used as image sources:

    HTMLImageElement (img elements)
    HTMLVideoElement (video elements)
    HTMLCanvasElement (canvas elements)
    CanvasRenderingContext2D
    ImageBitmap

The ImageBitmap interface can be created from a number of other image-representing types, including ImageData.

When a user agent is required to check the usability of the image argument, where image is a CanvasImageSource object, the user agent must run these steps, which return either good, bad, or aborted:

    If the image argument is an HTMLImageElement object that is in the broken state, then throw an InvalidStateError exception, return aborted, and abort these steps.

    If the image argument is an HTMLImageElement object that is not fully decodable, or if the image argument is an HTMLVideoElement object whose readyState attribute is either HAVE_NOTHING or HAVE_METADATA, then return bad and abort these steps.

    If the image argument is an HTMLImageElement object with an intrinsic width or intrinsic height (or both) equal to zero, then return bad and abort these steps.

    If the image argument is an HTMLCanvasElement object with either a horizontal dimension or a vertical dimension equal to zero, then return bad and abort these steps.

    Return good.

**Comment by zenozeng** [comment]
Since in chrome dataurl image are ready immediately, it should work in Chrome. But for firefox users, maybe give them a warning. For now?

**Comment by zenozeng** [comment]
Or maybe:

```
  loadImage(SVGGraphics, function(img) {
    image(img, 0, 0);
  });
```

**Comment by zenozeng** [comment]
Current implementation: 
```javascript
pg = createGraphics(400, 400, SVG);
background(200);
pg.background(100);
pg.noStroke();
pg.ellipse(pg.width/2, pg.height/2, 50, 50);
loadGraphics(pg, function(pg) {
    image(pg, 50, 50);
    image(pg, 0, 0, 50, 50);
});
```
