### ISSUE TITLE
createSVG or createCanvas

### ISSUE THREAD

**Issue by zenozeng** [zenozeng/p5.js-svg#81]
Since p5.js v0.4.7 provide p5.Renderer and use createCanvas(w, h, P2D) or createCanvas(w, h, WEBGL) for 2d/3d. Maybe we should use createCanvas(w, h, SVG) instead of using createSVG?

**Comment by zenozeng** [comment]
@dannewoo

**Comment by dannewoo** [comment]
Yes. I think its probably best to keep it consistant to avoid confussion. Looking good!

**Comment by zenozeng** [comment]
Fixed in https://github.com/zenozeng/p5.js-svg/commit/9c49e1b6110c63241bb51a593f9d73c25213c26e
